USE [WorkshopManager_DB]
GO

/****** Object:  Table [dbo].[tbl_REFRESH_TOKENS]    Script Date: 03.05.2021 15:22:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbl_REFRESH_TOKENS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[TOKEN] [varchar](500) NOT NULL,
	[EXPIRY_DATE] [date] NOT NULL,
 CONSTRAINT [PK_tbl_RefreshTokens] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[tbl_REFRESH_TOKENS]  WITH CHECK ADD  CONSTRAINT [FK_tbl_USERS_tbl_REFRESH_TOKENS] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[tbl_USERS] ([ID])
GO

ALTER TABLE [dbo].[tbl_REFRESH_TOKENS] CHECK CONSTRAINT [FK_tbl_USERS_tbl_REFRESH_TOKENS]
GO


